#!/usr/bin/env bash
#PBS -q sequentiel
#PBS -l mem=400G
#PBS -l walltime=96:00:00
#PBS -W umask=002
#PBS -l ncpus=1

########################################
##        Manage script history       ##
########################################

TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)
LOG="SelectNZV-AGC"_"$TIMESTAMP"".log"

########################################
##          Load environment          ##
########################################
# ADAPT to your tool

. /appli/bioinfo/R/4.2.1/env.sh

########################################
##          Execute script            ##
########################################

WORKDIR=/home/datawork-lmee-intranet-nos/ACE/06-STATS-GENE-MAT/R_scripts
LOGDIR=/home/datawork-lmee-intranet-nos/ACE/06-STATS-GENE-MAT/00-LOGS
cd $WORKDIR

Rscript Select_NZV_clusters_noVST_TMAX60.R >& $LOGDIR/$LOG 2>&1

