#!/usr/bin/env bash
#PBS -q omp
#PBS -l mem=1000G
#PBS -l walltime=48:00:00
#PBS -W umask=002
#PBS -l ncpus=2

########################################
##        Manage script history       ##
########################################

TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)
LOG="SelectNZV-AGC-VST"_"$TIMESTAMP"".log"

########################################
##          Load environment          ##
########################################
# ADAPT to your tool

. /appli/bioinfo/R/4.1.1/env.sh

########################################
##          Execute script            ##
########################################

WORKDIR=/home/datawork-lmee-intranet-nos/ACE/06-STATS-GENE-MAT/R_scripts
LOGDIR=/home/datawork-lmee-intranet-nos/ACE/06-STATS-GENE-MAT/00-LOGS
cd $WORKDIR

Rscript Select_NZV_clusters.R >& $LOGDIR/$LOG 2>&1

