#!/usr/bin/env bash
#PBS -q sequentiel
#PBS -l mem=20G
#PBS -l walltime=10:00:00
#PBS -W umask=002
#PBS -l ncpus=1

########################################
##        Manage script history       ##
########################################

TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)
LOG="RetrieveCagsAnnot"_"$TIMESTAMP"".log"

########################################
##          Load environment          ##
########################################
# ADAPT to your tool

########################################
##          Execute script            ##
########################################

WORKDIR=/home/datawork-lmee-intranet-nos/ACE/07-STATS-CAGs-OF-INTEREST
LOGDIR=/home/datawork-lmee-intranet-nos/ACE/07-STATS-CAGs-OF-INTEREST/00_logs
cd $WORKDIR

awk 'BEGIN{FS=OFS="\t"}NR==1{print $0}NR>1{$2="AGC_"$2; print $0}' /home/datawork-lmee-intranet-nos/ACE/Megahit_single_assembly/output_anvio_REF/07_GENE_MATRICES/Annotation_Table_AGN_CDH_Tax_KEGG_EGG.tsv > Annotation_Table_AGN_CDH_Tax_KEGG_EGG.tsv

