#!/usr/bin/env bash
#PBS -q sequentiel
#PBS -l mem=15G
#PBS -l walltime=1:30:00
#PBS -W umask=002
#PBS -l ncpus=1
#PBS -J 1-218

########################################
##      Manage script history         ##
########################################
TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)
LOG1="AGREG_PerSample_bash"_"$TIMESTAMP"".alone.log"

########################################
##      Load environment              ##
########################################

########################################
##      Execute script                ##
########################################

WORKDIR=/home/datawork-lmee-intranet-nos/ACE/Megahit_single_assembly/output_anvio_REF/07_GENE_MATRICES
NCOL=$((${PBS_ARRAY_INDEX}+1))
cd $WORKDIR

awk -F'\t' 'BEGIN{OFS="\t";}(NR==1){print $0}(NR>1){          # Call awk, set Output field separator       
    if (a[$1] == "") {
        a[$1] = $2
    }
    if (a[$1] < $2) {
        a[$1]=$2
    }
} END {
    for (i in a) {
        print i, a[i]
    }
}' <(cut -f1,$NCOL AGNOSTOS_GENE_MAT_DET.tsv) > AGNOSTOS_GENE_MAT_DET_Maximum.tsv_col_"$NCOL"



